---
- name: Install NGINX
  become: true
  apt:
    name: ['nginx']
    install_recommends: yes
  notify:
    - restart_nginx

- name: Configure service
  systemd:
    name: nginx
    enabled: yes
    state: started
  notify:
    - restart_nginx
