- name:
  become: true
  sysctl:
    name: sys.fs.file-max
    sysctl_set: yes
    value: 1204000
    state: present
    reload: yes

- name:
  become: true
  sysctl:
    name: net.core.somaxconn
    sysctl_set: yes
    value: 65535
    state: present
    reload: yes
